### ISSUE TITLE
Doesn't matter what you enter, can't register on public Instances of this server

### ISSUE THREAD

**Issue by joergister** [tigase/tigase-server#17]
**Describe the bug**
Registering on one of the domains tigase.im or sure.im is not possible.

**To Reproduce**
In case you are already logged into an XMPP account on BeagleIM or Siskin IM, and you try to add another account, chose create another account, chose tigase.im or sure.im and try to register.
On the public instances tigase.im and sure.im , one can not register. It doesn't matter if you enter for a username "whaterver" or "whatever@domain.im". you can add whatever email address from whatever email provider, it doesn't work. Also with password, you can use lowercase letters, uppercase letters, numbers, special symbols, you can chose whether it is 8 or 100 characters long, every combination of the above mentioned doesn't work. 
The only message I get is, "Registration failed!  Provided values are not acceptable"

**Expected behavior**
a more meaningful error message would be great. It is not clear to the user at all, what is wanted.

**Desktop (please complete the following information):**
 - macOS 1015.3
- MacBook Pro 13" 2019

**Smartphone (please complete the following information):**
 - Device:  iPhone8
 - OS: iOS 13.3.1 and

**Comment by woj-tek** [comment]
Hi @joergister. Thank you for registering the issue - we are aware of it and it has been fixed. We will deploy it shortly. (#server-1114)

**Comment by joergister** [comment]
thanks for the fast reply. Very good to hear it will be not an issue anymore soon.
keep up the good work ;)

**Comment by woj-tek** [comment]
And the fix was deployed - feel free to try it out and recommend it to your friends :-)

**Comment by joergister** [comment]
it works ; ) thanks a lot. 
Actually I was reccomendet siskin, but yes I will, when I'm sure everything works the way it should (still have problems with push and omemo when texting with siskin and conversations, will report them in the appropriate places)
